app_core/urls.py
from django.urls import path #
from .views import * #

app_name = 'app_core'

urlpatterns = [
    path('', Home.as_view(),name='home'),
    path('ensino/<int:pk>', ListarSeriesNivel.as_view(), name='listar_series_nivel'),
    path('materiais/<int:pk>', ListarMateriaisSerie.as_view(), name='listar_materiais'),
    path('download/<int:pk>', MaterialDownload.as_view(), name='material_download'),
]

app_lembrete/urls.py
from django.urls import path #
from .views import * #

app_name = 'app_lembrete'

urlpatterns = [
    path('create/', LembreteCreate.as_view(), name='lembrete_create'),
    path('read/', LembreteList.as_view(), name='lembrete_read'),
    path('update/<int:pk>', LembreteUpdate.as_view(), name='lembrete_update'),
    path('delete/<int:pk>', LembreteDelete.as_view(), name='lembrete_delete'),
    path('detail/<int:pk>', LembreteDetail.as_view(), name='lembrete_detail'),
]

app_material/urls.py
from django.urls import path #
from .views import * #

app_name = 'app_material'

urlpatterns = [
    path('create/', MaterialCreate.as_view(), name='material_create'),
    path('read/', MaterialList.as_view(), name='material_read'),
    path('update/<int:pk>', MaterialUpdate.as_view(), name='material_update'),
    path('delete/<int:pk>', MaterialDelete.as_view(), name='material_delete'),
    path('detail/<int:pk>', MaterialDetail.as_view(), name='material_detail'),
    path('download/<int:pk>', MaterialDownload.as_view(), name='material_download'),
]

mundodosaber/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings #
from django.conf.urls.static import static # para incluir diretórios MEDIA

urlpatterns = [
    path('',include('app_core.urls',namespace='app_core')),
    path('material/',include('app_material.urls','app_material')),
    path('lembrete/',include('app_lembrete.urls','app_lembrete')),
    path('restrito/admin/', admin.site.urls),
    #path('admin/restrito', admin.site.urls),
    #path('admin/', admin.site.urls),
]

# Apenas para servir arquivo de media em desenvolvimento
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('usuario/', include('django.contrib.auth.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Centro Educacional Mundo do Saber</title>
    <!-- Font Awesome icons (free version)-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
    <!-- Core theme CSS (includes Bootstrap 4)-->
     <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- Fonts CSS-->
    <link rel="stylesheet" href="{% static 'css/heading.css' %}">
    <link rel="stylesheet" href="{% static 'css/body.css' %}">
</head>
<body id="page-top">
<!-- BODY -->
    <!-- NAVBAR -->
    {% include 'navbar.html' %}
    <!-- HEADERs/SECTIONs/DIVs DE CONTEÚDOS -->
    {% block conteudo %}
    {% endblock %}
    <!-- FOOTER -->
    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
{% load static %}        
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Telefone -->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="mb-4">TELEFONE</h4>
                        <p class="lead mb-0">(79) 3254-9705</p>
                    </div>
                    <!-- Footer Redes Sociais e Endereço -->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="mb-4">REDES SOCIAIS E ENDEREÇO</h4>
                        <a class="btn btn-outline-light btn-social mx-1" href="https://www.instagram.com/colegiomundosaber/">
                            <i class="fab fa-fw fa-instagram"></i>
                        </a>
                        <a class="btn btn-outline-light btn-social mx-1" href="mailto:serginho.manhae@gmail.com">
                            <i class="fas fa-envelope pr-1"></i>
                        </a>
                        <a class="btn btn-outline-light btn-social mx-1" href="https://www.youtube.com/channel/UC-elJVvg2VPDTKOau20MCEQ">
                            <i class="fab fa-youtube pr-1"></i>
                        </a>
                        <br><br>
                        <p>Rua 51 nº 348 - Bairro Taiçoca<br>Nossa Sra. do Socorro - SE<br>CEP: 49160-000</p>
                    </div>
                    <!-- Footer Localização -->
                    <div class="col-lg-4">
                        <h4 class="mb-4">LOCALIZAÇÃO</h4>
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.697547935709!2d-37.08244298545465!3d-10.834442023480955!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x7054c53a0ac7da9%3A0xe2138c209971025f!2sCentro%20Educacional%20Mundo%20do%20Saber!5e0!3m2!1spt-BR!2sbr!4v1588647587640!5m2!1spt-BR!2sbr" width="250" height="200" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        <section class="copyright py-4 text-center text-white">
            <div class="container">
                <div>
                    <small class="pre-wrap">Copyright ©</small>
                </div>
                <div>
                    <small class="pre-wrap">Sérgio&nbsp;&nbsp;<i class="fas fa-mobile-alt"></i>&nbsp;(79) 98122-7820  /  Paulo&nbsp;&nbsp;<i class="fas fa-mobile-alt"></i>&nbsp;(79) 98802-4266</small>
                </div>
                <div>
                {% if acessos %}
                    <small class="pre-wrap">Versão 1.0 - Ano 2020 - Acessos {{ acessos | stringformat:'04d' }}</small>
                {% else %}
                    <small class="pre-wrap">Versão 1.0 - Ano 2020</small>
                {% endif %}
                </div>
            </div>
        </section>
        <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes)-->
        <div class="scroll-to-top position-fixed"><a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top"><i class="fa fa-chevron-up"></i></a></div>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Contact form JS-->
        <script src="{% static 'assets/mail/jqBootstrapValidation.js' %}"></script>
        <script src="{% static 'assets/mail/contact_me.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>

templates/navbar.html
{% load static %}
        <nav class="navbar navbar-expand-lg bg-secondary fixed-top" id="mainNav">
            <div class="container"><a class="navbar-brand js-scroll-trigger" href="#page-top"><img src="{% static 'assets/img/logoalterada.png' %}" alt="Topo da Página" title="Voltar para o topo da página" width="65px"></a>
                <button class="navbar-toggler navbar-toggler-right font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">Menu <i class="fas fa-bars"></i></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'app_core:home' %}">HOME</a>
                        </li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'app_core:listar_series_nivel' 1 %}">EDUCAÇÃO INFANTIL</a>
                        </li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'app_core:listar_series_nivel' 2 %}">FUNDAMENTAL I</a>
                        </li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'app_core:listar_series_nivel' 3 %}">FUNDAMENTAL II</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle nav-link py-3 px-0 px-lg-3 rounded" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">MATERIAL</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown01">
                                <a class="dropdown-item" href="{% url 'app_material:material_create' %}">Cadastrar</a>
                                <a class="dropdown-item" href="{% url 'app_material:material_read' %}">Listar/Editar</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle nav-link py-3 px-0 px-lg-3 rounded" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">LEMBRETE</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown02">
                                <a class="dropdown-item" href="{% url 'app_lembrete:lembrete_create' %}">Cadastrar</a>
                                <a class="dropdown-item" href="{% url 'app_lembrete:lembrete_read' %}">Listar/Editar</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle nav-link py-3 px-0 px-lg-3 rounded" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Usuário: {{ user.get_username }}</a>
                           <div class="dropdown-menu" aria-labelledby="dropdown02">
                            <a class="dropdown-item" href="{% url 'logout' %}?next={{request.path}}">Logout</a>
                           </div>
                        </li> 
                        {% else %}
                        <li class="nav-item mx-0 mx-lg-1"> 
                            <a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'login' %}?next={{request.path}}">Login</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>